name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make check
      run: cd lua-tests && sh run_tests.sh ../build/ravi
